[build]
  publish = "_site"
  command = "bundle exec jekyll build"

# Enable Identity
[build.environment]
  RUBY_VERSION = "3.3.9"

# Redirect rules for protected pages
[[redirects]]
  from = "/members/*"
  to = "/members/:splat"
  status = 200
  force = false
  conditions = {Role = ["member", "admin"]}

# Netlify CMS admin panel
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200